#######################
# Lemmatization errors
#######################

def get_it_lemma_errors():
    lemma_errors = {
                    'accetta': {'NOUN': 'accetta',
                                'VERB': 'accettare'},
                    'accetto': {'VERB': 'accettare'},
                    'agente': {'NOUN': 'agente'},
                    'agenti': {'NOUN': 'agente'},
                    'ancora': {'ADV': 'ancora'},
                    'assassini': {'ADJ': 'assassino',
                                  'NOUN': 'assassino'},
                    'assassino': {'ADJ': 'assassino',
                                  'NOUN': 'assassino'},
                    'avra': {'AUX': 'essere',
                             'VERB': 'essere'},
                    'bel': {'ADJ': 'bello'},
                    'caduti': {'ADJ': 'caduto'},
                    'caduto': {'ADJ': 'caduto'},
                    'capitano': {'NOUN': 'capitano'},
                    'centro': {'ADV': 'centro',
                               'NOUN': 'centro'},
                    'collo': {'NOUN': 'collo'},
                    'complimento': {'NOUN': 'complimento'},
                    'complimenti': {'NOUN': 'complimenti'},
                    'confine': {'NOUN': 'confine'},
                    'confini': {'NOUN': 'confine'},
                    'dei': {'DET': 'del'},
                    'delinquente': {'ADJ': 'delinquente',
                                    'NOUN': 'delinquente'},
                    'delinquenti': {'ADJ': 'delinquente',
                                    'NOUN': 'delinquente'},
                    'difesa': {'NOUN': 'difesa'},
                    'difese': {'NOUN': 'difesa'},
                    'dire': {'AUX': 'dire',
                             'VERB': 'dire'},
                    'duro': {'ADJ': 'duro'},
                    'faccia': {'NOUN': 'faccia'},
                    'fate': {'AUX': 'fare',
                             'VERB': 'fare'},
                    'fatto': {'NOUN': 'fatto'},
                    'forza': {'NOUN': 'forza'},
                    'giudice': {'NOUN': 'giudice'},
                    'giudici': {'NOUN': 'giudice'},
                    'governi': {'NOUN': 'governo'},
                    'governo': {'NOUN': 'governo'},
                    'ignorante': {'ADJ': 'ignorante',
                                  'NOUN': 'ignorante'},
                    'ignoranti': {'ADJ': 'ignorante',
                                  'NOUN': 'ignorante'},
                    'incendio': {'NOUN': 'incendio'},
                    'lega': {'NOUN': 'lega'},
                    'legge': {'NOUN': 'legge'},
                    'leggi': {'NOUN': 'legge'},
                    'libro': {'NOUN': 'libro'},
                    'lotta': {'NOUN': 'lotta'},
                    'luce': {'NOUN': 'luce'},
                    'luci': {'NOUN': 'luce'},
                    'mente': {'NOUN': 'mente'},
                    'menti': {'NOUN': 'mente'},
                    'minimo': {'ADJ': 'minimo'},
                    'nei': {'DET': 'nei'},
                    'odio': {'NOUN': 'odio'},
                    'oli': {'NOUN': 'olio'},
                    'olio': {'NOUN': 'olio'},
                    'ora': {'ADV': 'ora'},
                    'pacifico': {'ADJ': 'pacifico'},
                    'parente': {'NOUN': 'parente'},
                    'parenti': {'NOUN': 'parente'},
                    'parte': {'NOUN': 'parte'},
                    'parti': {'NOUN': 'parte'},
                    'partiti': {'NOUN': 'partito'},
                    'partito': {'NOUN': 'partito'},
                    'patria': {'NOUN': 'patria'},
                    'piazza': {'NOUN': 'piazza'},
                    'piazze': {'NOUN': 'piazza'},
                    'popoli': {'NOUN': 'popolo'},
                    'popolo': {'NOUN': 'popolo'},
                    'porta': {'NOUN': 'porta',
                              'VERB': 'portare'},
                    'porte': {'NOUN': 'porta'},
                    'proposta': {'NOUN': 'proposta'},
                    'rappresentante': {'NOUN': 'rappresentante'},
                    'rappresentanti': {'NOUN': 'rappresentante'},
                    'resto': {'NOUN': 'resto'},
                    'ridono': {'VERB': 'ridere'},
                    'salario': {'NOUN': 'salario'},
                    'salari': {'NOUN': 'salario'},
                    'saluto': {'NOUN': 'saluto'},
                    'sara': {'VERB': 'essere'},
                    'schifo': {'NOUN': 'schifo'},
                    'scintilla': {'NOUN': 'scintilla'},
                    'scontrini': {'NOUN': 'scontrino'},
                    'scontrino': {'NOUN': 'scontrino'},
                    'scritta': {'NOUN': 'scritta'},
                    'scritte': {'NOUN': 'scritta'},
                    'serpi': {'NOUN': 'serpe'},
                    'servo': {'NOUN': 'servo'},
                    'significato': {'NOUN': 'significato'},
                    'sinistra': {'ADJ': 'sinistra',
                                 'NOUN': 'sinistra'},
                    'sole': {'NOUN': 'sole',
                             'ADJ': 'solo'},
                    'solo': {'ADV': 'solo'},
                    'subito': {'ADV': 'subito'},
                    'tanta': {'ADJ': 'tanto',
                              'ADV': 'tanto'},
                    'tante': {'ADJ': 'tanto',
                              'ADV': 'tanto'},
                    'tanti': {'ADJ': 'tanto',
                              'ADV': 'tanto'},
                    'tanto': {'ADJ': 'tanto',
                              'ADV': 'tanto'},
                    'tassa': {'NOUN': 'tassa'},
                    'tasse': {'NOUN': 'tassa'},
                    'vai': {'AUX': 'andare',
                            'VERB': 'andare'},
                    'vergogna': {'NOUN': 'vergogna'},
                    'viaggi': {'NOUN': 'viaggio'},
                    'viaggio': {'NOUN': 'viaggio'},
                    'vista': {'NOUN': 'vista'},
                    'volante': {'NOUN': 'volante'}
                    }
                    
    return lemma_errors
